services:
    backend:
        build:
            context: .
            dockerfile: ./server/Dockerfile.compose
        ports:
            - "5234:8080"
        volumes:
            - ./server/Data:/app/Data
        networks:
            - codecomments-network

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile.compose
        ports:
            - "5000:80"
        depends_on:
            - backend
        networks:
            - codecomments-network

networks:
    codecomments-network:
        driver: bridge
