name: Deploy Vue app to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        if: github.ref != 'refs/heads/gh-pages'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              working-directory: project/frontend
              run: npm install

            - name: Build Vue app
              working-directory: project/frontend
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: project/frontend/dist
                  force_orphan: true
