name: Deploy FE to GitHub Pages

on:
    push:
        branches: [deploy/gh-pages]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 22

            - run: npm ci
              working-directory: frontend

            - run: npm run build
              working-directory: frontend
              env:
                  VITE_API_BASE_URL: "http://localhost/server"

            - run: cp index.html 404.html
              working-directory: frontend/dist

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./frontend/dist
