name: Build and deploy ASP.Net Core app to Azure Web App - codecommentsdemo

on:
  push:
    branches:
      - feat/auto-azure-deployment
  workflow_dispatch:

env:
  PROJECT_PATH: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore $PROJECT_PATH

      - name: Build
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore

      - name: Publish
        run: dotnet publish $PROJECT_PATH -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5AD5A552A984FE9A3C3A78FDAB4D9CC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D51A06BAD1BF4E8A9C751FBBE0ED605D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3A76EB4B45C407AB527A8C47E8A8A78 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'codecommentsdemo'
          slot-name: 'Production'
          package: ${{ github.workspace }}
